version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
#    ports:
#      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      TZ: "Asia/Shanghai"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--protocol=tcp"]
      timeout: 20s
      interval: 1s
      retries: 20
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci'
    ]

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  testing:
    container_name: testing
    image: golang:1.15
    working_dir: /opt/myapp/
    volumes:
      - $PWD:/opt/myapp/
    depends_on:
      - mysql
      - redis
    command: >
      bash -c "
      go env -w GOPROXY=https://goproxy.cn,direct
      && go test ./... -v
      "
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_DB: 1
      REDIS_PASS: ""

networks:
  default:
    name: mynetwork
    driver: bridge
