// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/kwstars/derasure/internal/app"
	"github.com/kwstars/derasure/internal/app/controllers"
	"github.com/kwstars/derasure/internal/app/model"
	"github.com/kwstars/derasure/internal/app/services"
	"github.com/kwstars/derasure/pkg/config"
	"github.com/kwstars/derasure/pkg/db"
	"github.com/kwstars/derasure/pkg/log"
	"github.com/kwstars/derasure/pkg/transports/http"
)

// Injectors from wire.go:

func CreateApp(confPath string) (*app.App, func(), error) {
	viper, err := config.New(confPath)
	if err != nil {
		return nil, nil, err
	}
	logOptions, err := log.NewLogOptions(viper)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := log.New(logOptions)
	if err != nil {
		return nil, nil, err
	}
	redisOptions, err := db.NewRedisOptions(viper)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := db.New(redisOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repostiory := &model.Repostiory{
		Redis: client,
	}
	eliminate := &services.Eliminate{
		Repostiory: repostiory,
	}
	banquet := &services.Banquet{
		Repostiory: repostiory,
	}
	fishing := &services.Fishing{
		Repostiory: repostiory,
	}
	kite := &services.Kite{
		Repostiory: repostiory,
	}
	limitedGift := &services.LimitedGift{
		Repostiory: repostiory,
	}
	servicesServices := services.Services{
		Logger:      logger,
		Eliminate:   eliminate,
		Banquet:     banquet,
		Fishing:     fishing,
		Kite:        kite,
		LimitedGift: limitedGift,
	}
	controller := &controllers.Controller{
		Service: servicesServices,
	}
	initControllers := controllers.CreateInitControllersFn(controller)
	engine := http.NewRouter(initControllers, logger)
	server, err := http.New(engine)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appApp, err := app.NewApp(server, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var providerSet = wire.NewSet(config.GlobalProviderSet, log.ProviderSet, db.ProviderSet, model.ProviderSet, services.ProviderSet, controllers.ProviderSet, http.ProviderSet, app.ProviderSet)
