// Code generated by "stringer -type RetNo -linecomment"; DO NOT EDIT.

package retno

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[INVALID_DATA-1]
	_ = x[UNAUTHORIZED-2]
	_ = x[INTERNAL_ERROR-3]
	_ = x[NOT_FOUND-4]
}

const _RetNo_name = "OK请求参数不正确无权限服务器内部错误无该资源"

var _RetNo_index = [...]uint8{0, 2, 23, 32, 53, 65}

func (i RetNo) String() string {
	if i < 0 || i >= RetNo(len(_RetNo_index)-1) {
		return "RetNo(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RetNo_name[_RetNo_index[i]:_RetNo_index[i+1]]
}
